site_name: irgsctool
site_url: ""
use_directory_urls: false
watch:
  - docs
theme: 
  name: material
  logo: TMT_LOGO.PNG
plugins:
  - mkdocstrings - python
  - glightbox
plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"
nav:
  - Home : index.md
  - About : about.md
  - UserGuide: userguide.md
  - API: apireference.md
  - License: license.md
  - Tutorials: tutorials.md

